name: Build BISDN Linux

on:
  push:
    branches:
      - rl_build
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install kas

      - name: Build BISDN Linux
        run: |
          kas-container build bisdn-linux.yaml

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bisdn-linux-image
          path: build/tmp/deploy/images/
