name: Build BISDN Linux

on:
  push:
    branches:
      - rl_build
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Inspect build host
        run: |
          lscpu
          echo .
          free -h
          echo .
          df -h
          echo .
          cat /etc/os-release
          sudo du -m / > du || true

      - name: Upload du
        uses: actions/upload-artifact@v4
        with:
          name: du
          path: du
